---
monitoring_loki_version: "3.0.0"
monitoring_promtail_version: "3.0.0"
monitoring_grafana_version: "12.3.1"
monitoring_prometheus_version: "v3.9.0"
monitoring_loki_port: 3100
monitoring_grafana_port: 3000
monitoring_promtail_port: 9080
monitoring_prometheus_port: 9090
monitoring_retention_period: "168h"
monitoring_prometheus_retention_time: "15d"
monitoring_prometheus_retention_size: "10GB"
monitoring_prometheus_scrape_interval: "15s"
monitoring_compose_dir: "/opt/monitoring"
monitoring_grafana_admin_password: "admin"
monitoring_app_python_target: "app-python:5000"
monitoring_app_python_port: 8000
