apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-info-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-info-vault
  template:
    metadata:
      labels:
        app: devops-info-vault
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "devops-info-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/devops-info/config"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/devops-info/config" -}}
          APP_USERNAME={{ .Data.data.username }}
          APP_PASSWORD={{ .Data.data.password }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-command-config: "sh -c 'kill -HUP 1'"
    spec:
      serviceAccountName: devops-info
      containers:
        - name: devops-info
          image: merkulovlr05/devops-info:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
          resources:
            requests:
              cpu: "50m"
              memory: "96Mi"
            limits:
              cpu: "200m"
              memory: "192Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
