apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: devops-info-set
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
            valuesFile: values-dev.yaml
            autoSync: "true"
          - env: prod
            namespace: prod
            valuesFile: values-prod.yaml
            autoSync: "false"
  template:
    metadata:
      name: 'devops-info-{{ .env }}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/merkulovleo/DevOps-Core-Course.git
        targetRevision: lab13
        path: k8s/helm/devops-info
        helm:
          valueFiles:
            - values.yaml
            - '{{ .valuesFile }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
