apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-info-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/merkulovleo/DevOps-Core-Course.git
    targetRevision: lab13
    path: k8s/helm/devops-info
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
