{{- if and .Values.rollout.enabled .Values.rollout.analysis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "devops-info.fullname" . }}-health-check
  labels:
    {{- include "devops-info.labels" . | nindent 4 }}
spec:
  metrics:
    - name: health-check
      provider:
        web:
          url: "http://{{ include "devops-info.fullname" . }}.{{ .Release.Namespace }}.svc/health"
          jsonPath: "{$.status}"
      successCondition: result == "healthy"
      interval: 10s
      count: 3
      failureLimit: 1
{{- end }}
