apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-info.fullname" . }}-config
  labels:
    {{- include "devops-info.labels" . | nindent 4 }}
data:
  config.json: |-
{{ .Files.Get "files/config.json" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-info.fullname" . }}-env
  labels:
    {{- include "devops-info.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.appEnv | default "development" | quote }}
  LOG_LEVEL: {{ .Values.logLevel | default "INFO" | quote }}
  VISITS_FILE: "/data/visits"
