apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-info.fullname" . }}-secret
  labels:
    {{- include "devops-info.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_USERNAME: {{ .Values.secret.username | quote }}
  APP_PASSWORD: {{ .Values.secret.password | quote }}
